import api from './api';

const PLANT_CACHE_KEY = 'durango';
const cache = new Map();
const inFlight = new Map();
const CURRENT_TTL_MS = 25 * 1000;
const TODAY_TTL_MS = 60 * 1000;
const HISTORY_TTL_MS = 10 * 60 * 1000;
const MONTHLY_TTL_MS = 30 * 60 * 1000;

function optionBoolean(primary, fallback, defaultValue) {
  if (typeof primary === 'boolean') return primary;
  if (typeof fallback === 'boolean') return fallback;
  return defaultValue;
}
function localToday() { const now = new Date(); const offset = now.getTimezoneOffset() * 60000; return new Date(now.getTime() - offset).toISOString().slice(0, 10); }
function rangeIncludesToday(start, end) { if (!start && !end) return false; const today = localToday(); const first = start || end || ''; const last = end || start || ''; return first <= today && today <= last; }
function buildParams(options = {}) { const params = {}; if (options.startDate || options.start_date) params.start_date = String(options.startDate || options.start_date); if (options.endDate || options.end_date) params.end_date = String(options.endDate || options.end_date); if (options.period) params.period = String(options.period); params.include_history = optionBoolean(options.includeHistory, options.include_history, true); params.include_energy_water = optionBoolean(options.includeEnergyWater, options.include_energy_water, false); const force = optionBoolean(options.forceRefresh, options.force_refresh, false); if (force) params.force_refresh = true; return params; }
function cacheTtl(params) { if (params.include_history === false && !params.start_date && !params.end_date) return CURRENT_TTL_MS; if (String(params.period || '').toLowerCase() === 'monthly') return MONTHLY_TTL_MS; if (rangeIncludesToday(params.start_date, params.end_date)) return TODAY_TTL_MS; return params.include_history === false ? CURRENT_TTL_MS : HISTORY_TTL_MS; }
function cacheKey(section, options = {}) { const params = buildParams(options); return [PLANT_CACHE_KEY, section, params.start_date || '', params.end_date || '', params.period || '', params.include_history === false ? 'current' : 'history', params.include_energy_water ? 'energy' : 'no-energy'].join(':'); }
async function cachedRequest(key, ttl, forceRefresh, loader) { const now = Date.now(); const cached = cache.get(key); if (!forceRefresh && cached && now - cached.ts < cached.ttl) return cached.data; const pending = inFlight.get(key); if (pending) return pending; if (forceRefresh) cache.delete(key); const request = loader().then((data) => { cache.set(key, { ts: Date.now(), ttl, data }); return data; }).finally(() => { if (inFlight.get(key) === request) inFlight.delete(key); }); inFlight.set(key, request); return request; }
export function clearWaterCache() { cache.clear(); }
export async function fetchWaterDashboard(section = 'dashboard', options = {}) { const params = buildParams(options); const key = cacheKey(section, options); return cachedRequest(key, cacheTtl(params), params.force_refresh, async () => (await api.get(`/water/dashboard/${section}`, { params, timeout: 12000 })).data); }
export async function fetchWaterHistory(options) { const key = [PLANT_CACHE_KEY, 'history', options.module, String(options.sensorId), options.startDate, options.endDate, options.aggregation].join(':'); const ttl = rangeIncludesToday(options.startDate, options.endDate) ? TODAY_TTL_MS : HISTORY_TTL_MS; return cachedRequest(key, ttl, options.forceRefresh, async () => (await api.get('/water/history', { params: { module: options.module, sensor_id: options.sensorId, start_date: options.startDate, end_date: options.endDate, aggregation: options.aggregation, force_refresh: Boolean(options.forceRefresh) }, timeout: 30000 })).data); }
export async function fetchWaterModuleHistory(options) { const key = [PLANT_CACHE_KEY, 'history-module', options.module, options.startDate, options.endDate, options.aggregation].join(':'); const ttl = rangeIncludesToday(options.startDate, options.endDate) ? TODAY_TTL_MS : HISTORY_TTL_MS; return cachedRequest(key, ttl, options.forceRefresh, async () => (await api.get('/water/history/module', { params: { module: options.module, start_date: options.startDate, end_date: options.endDate, aggregation: options.aggregation, force_refresh: Boolean(options.forceRefresh) }, timeout: 30000 })).data); }
export async function fetchWellsMinuteFlow(options) { const key = [PLANT_CACHE_KEY, 'wells-minute', options.startDateTime, options.endDateTime].join(':'); const ttl = rangeIncludesToday(options.startDateTime.slice(0, 10), options.endDateTime.slice(0, 10)) ? TODAY_TTL_MS : HISTORY_TTL_MS; return cachedRequest(key, ttl, options.forceRefresh, async () => (await api.get('/water/wells/minute-flow', { params: { start_datetime: options.startDateTime, end_datetime: options.endDateTime, force_refresh: Boolean(options.forceRefresh) }, timeout: 30000 })).data); }
export async function fetchWaterShifts(options) { const key = [PLANT_CACHE_KEY, 'shifts', options.date, options.shift || 'all'].join(':'); const ttl = options.date === localToday() ? TODAY_TTL_MS : HISTORY_TTL_MS; return cachedRequest(key, ttl, options.forceRefresh, async () => (await api.get('/water/shifts', { params: { date: options.date, shift: options.shift || 'all', force_refresh: Boolean(options.forceRefresh) }, timeout: 30000 })).data); }
export async function fetchWaterDailyReview(options = {}) { const key = [PLANT_CACHE_KEY, 'review-daily', options.date || '', options.includeShifts === false ? 'no-shifts' : 'shifts', options.includeComparatives === false ? 'no-comparatives' : 'comparatives'].join(':'); const ttl = (options.date || localToday()) === localToday() ? TODAY_TTL_MS : HISTORY_TTL_MS; return cachedRequest(key, ttl, options.forceRefresh, async () => (await api.get('/water/review/daily', { params: { date: options.date || undefined, include_shifts: options.includeShifts !== false, include_comparatives: options.includeComparatives !== false, force_refresh: Boolean(options.forceRefresh) }, timeout: 45000 })).data); }
export async function fetchWaterReportCatalog(options = {}) { return (await api.get('/water/reports/catalog', { params: buildParams(options) })).data; }
export async function fetchWaterSources() { return (await api.get('/water/sources')).data; }
export async function validateWaterSource(file) { const formData = new FormData(); formData.append('file', file); return (await api.post('/water/sources/validate', formData, { headers: { 'Content-Type': 'multipart/form-data' } })).data; }
export async function uploadWaterSource(file, activate = true) { const formData = new FormData(); formData.append('file', file); const data = (await api.post(`/water/sources/upload?activate=${activate}`, formData, { headers: { 'Content-Type': 'multipart/form-data' } })).data; clearWaterCache(); return data; }
export async function activateWaterSource(sourceId) { const data = (await api.post(`/water/sources/${sourceId}/activate`)).data; clearWaterCache(); return data; }
